"""add tg_user, hire_date

Revision ID: 3a6dc3934ae4
Revises: f9b93936acbd
Create Date: 2025-12-22 10:00:04.313118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a6dc3934ae4'
down_revision: Union[str, Sequence[str], None] = 'f9b93936acbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hire_date', sa.Date(), nullable=True))
    op.add_column('users', sa.Column('telegram_username', sa.String(length=128), nullable=True))
    op.create_unique_constraint(None, 'users', ['telegram_username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'telegram_username')
    op.drop_column('users', 'hire_date')
    # ### end Alembic commands ###
