"""update_courses_table

Revision ID: 46118e0f054d
Revises: 6c350c83b741
Create Date: 2026-01-10 12:37:54.513250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '46118e0f054d'
down_revision: Union[str, Sequence[str], None] = '6c350c83b741'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('modules')
    op.add_column('courses', sa.Column('short_description', sa.Text(), nullable=True))
    op.add_column('courses', sa.Column('duration_hours', sa.Integer(), nullable=False))
    op.add_column('courses', sa.Column('tags', sa.JSON(), nullable=True))
    op.add_column('courses', sa.Column('requirements', sa.JSON(), nullable=True))
    op.add_column('courses', sa.Column('what_you_learn', sa.JSON(), nullable=True))
    op.alter_column('courses', 'status',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('departments', 'company_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('lessons', sa.Column('course_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('lessons_module_id_fkey'), 'lessons', type_='foreignkey')
    op.create_foreign_key(None, 'lessons', 'courses', ['course_id'], ['id'], ondelete='CASCADE')
    op.drop_column('lessons', 'module_id')
    op.alter_column('questions', 'test_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('questions', 'question_text',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               nullable=False)
    op.alter_column('questions', 'question_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(op.f('uq_roles_title'), 'roles', type_='unique')
    op.alter_column('tests', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('tests', 'course_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tests', 'course_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('tests', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.create_unique_constraint(op.f('uq_roles_title'), 'roles', ['title'], postgresql_nulls_not_distinct=False)
    op.alter_column('questions', 'question_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('questions', 'question_text',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               nullable=True)
    op.alter_column('questions', 'test_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('lessons', sa.Column('module_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'lessons', type_='foreignkey')
    op.create_foreign_key(op.f('lessons_module_id_fkey'), 'lessons', 'modules', ['module_id'], ['id'], ondelete='CASCADE')
    op.drop_column('lessons', 'course_id')
    op.alter_column('departments', 'company_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('courses', 'status',
               existing_type=sa.String(length=20),
               type_=sa.BOOLEAN(),
               existing_nullable=False)
    op.drop_column('courses', 'what_you_learn')
    op.drop_column('courses', 'requirements')
    op.drop_column('courses', 'tags')
    op.drop_column('courses', 'duration_hours')
    op.drop_column('courses', 'short_description')
    op.create_table('modules',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_published', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('modules_course_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('modules_pkey'))
    )
    # ### end Alembic commands ###
